#Hugo configuration
title = "sadfdsf"
baseURL = "https:\/\/ds.fdsa.fasd"
languageCode = "en-us"
theme = "tvpage"
disablePathToLower = "true"
enableRobotsTXT = true

[params]
loginId = "1758403"
subfolder = ""
firstpartycookies = true
cookiedomain = "fdsa.fasd"
